Arnah
onja-madagascar/music-of-madagascar pull request #168
Opened 2020-01-30 13:17 UTC by Ny-Rianala

Hey,

I added a new file, please have a look and let me know if something went wrong.

Thanks.
Kati

2020-01-30 13:49 UTC, ndorfin requested changes

2020-01-30 13:49 UTC, ndorfin commented on a/arnah.md
> +![Arnah](arnah.jpg)
This is lowercase, correct.
But the filename of the image has a capital letter!

2020-01-31 06:28 UTC, ndorfin requested changes
The image filename needs to use a lowercase 'a' please.

2020-01-31 08:41 UTC, Ny-Rianala commented
Hey,
I fixed the image filename, please have a look at it and let me know if there are things which I need to change.
Thanks,
Kati

2020-01-31 08:46 UTC, ndorfin requested changes
Needs a markdown file

2020-01-31 11:38 UTC, ndorfin approved these changes
Well done!

2020-01-31 14:14 UTC, ndorfin approved these changes

2020-01-31 14:14 UTC, merged