Added brams.md
onja-madagascar/music-of-madagascar pull request #246
Opened 2020-01-31 13:19 UTC by Voninkazo

Hey, 
Could please check my PR and suggest any changes, I looked for the information, but there wasn't.

Thanks
Sandy

2020-01-31 14:11 UTC, ndorfin requested changes

2020-01-31 14:11 UTC, ndorfin commented on b/brams.md
> +Unfortunately, we could not find any information about this singer. We only found his homepage, so you can have a lookat that.
`look at`

2020-01-31 15:10 UTC, Voninkazo commented
I've made the change,
Could you please check again.

2020-02-01 05:24 UTC, ndorfin approved these changes
Looks good. Ship-it!

2020-02-01 05:25 UTC, Voninkazo commented
Thank you.

2020-02-01 05:25 UTC, merged